autowarefoundation/autoware-github-actions

.github/workflows/automatic-rebase.yaml
=> ci(automatic-rebase): use token for checkout

colcon-build-and-test/action.yaml
Added coverage related commands to `colcon-build-and-test` action.
Now I'm evaluating lcov and codecov workflows at https://github.com/KeisukeShima/autoware.universe/actions/runs/1738065485
Related https://github.com/autowarefoundation/autoware.universe/issues/286
=> feat(colcon-build-and-test): add coverage-related commands

colcon-build-and-test/action.yaml
Add `packages-above` option to `colcon lcov-result` and colcon `coveragepy-result`
This PR solves the error that occurs with `build-and-test-pr`.
https://github.com/autowarefoundation/autoware.universe/runs/4931225179?check_suite_focus=true
=> fix(colcon-build-and-test): add option to colcon lcov-result

colcon-build-and-test/action.yaml
Added a command to install the `lcov` package in order to run the `colcon lcov-result` command.
=> fix(colcon-build-and-test): add lcov package

colcon-build-and-test/action.yaml
`colcon lcov-result` will return an non-zero error code if the `coverage.info` file does not exist.
https://github.com/colcon/colcon-lcov-result/blob/master/colcon_lcov_result/verb/lcov_result.py#L128
It occurs a CI error.
https://github.com/autowarefoundation/autoware_common/runs/4945733047?check_suite_focus=true
To avoid this error, I have added a file check statement before executing the command. 
=> fix(colcon-build-and-test): add file check statement and use colcon-mixin

.github/sync-files.yaml, .github/workflows/sync-files.yaml, sync-files/README.md, sync-files/action.yaml, sync-files/parse_config.py
Since Autoware has multiple repositories, it's useful to sync files between repositories to keep their settings the same.
[BetaHuhn/repo-file-sync-action](https://github.com/BetaHuhn/repo-file-sync-action) or [kbrashears5/github-action-file-sync](https://github.com/kbrashears5/github-action-file-sync) is useful for this use case, which I think we can call `push-style` action.
However, I'd like to add a `pull-style` action.
It's useful when a contributor has an Autoware's extension repository and doesn't want to manage a central repository for the settings like https://github.com/BetaHuhn/github-files or https://github.com/kbrashears5/kbrashears5.
Regarding the sync of community health files, We can consider using `.github` repository. …
=> feat: add sync-files action

colcon-build-and-test/action.yaml
Resolves https://github.com/autowarefoundation/autoware_common/runs/4971375103?check_suite_focus=true
Since the colcon mixin repository is already set up in ros:galactic image, I removed the duplicate step. 
In other ros2 environments such as `ros-tooling/setup-ros`, the colcon mixin is not set up. Therefore, it need to be set up manually by the user.
https://hub.docker.com/layers/ros/library/ros/galactic/images/sha256-d52ee1b0d65d7df83a4897c39568d6a450a10d76c330450c90ae0e79e4c0d2a8?context=explore
=> fix(colcon-build-and-test): ignore errors in colcon mixin step

sync-branches/README.md, sync-branches/action.yaml
Autoware Core and Universe have multiple repositories so that users can easily customize/extend Autoware.
Suppose that a company uses `autowarefoundation/autoware` and fork it to `some-company/autoware`.
In that case, it is useful if we can sync branches making `autowarefoundation/autoware` as a base.
https://github.com/wei/pull is useful for this use case, but it works only in the fork network.
Therefore, for example, it doesn't work if users manually fork repositories in multiple stages and make them private.
=> feat: add sync-branches action

colcon-build-and-test/action.yaml
Changed the `colcon lcov-result` command to always be executed.
Before the change, the condition to check the existence of the `coverage.info` file was not working correctly. This is because the `colcon lcov-result` command generates the `coverage.info` file. So the if statement was always false. 
After thinking about what kind of change I would like to make, I decided to simply ignore the return value. I also applied this change to `colcon coveragepy` to account for future API changes.
I will check this change in my forked repository. After confirming this change, I will post the result and change the state to ready for review.
=> fix(colcon-build-and-test): fix coverage commands

set-git-config/README.md, set-git-config/action.yaml
In #43, I split the step of `git config` into a composite action to reduce repetitions.
=> feat: add set-git-config action

colcon-build-and-test/action.yaml
Closes #47 
I have confirmed that this PR fixes the problem:
https://github.com/KeisukeShima/autoware.universe/runs/5048312036?check_suite_focus=true
=> fix(colcon-build-and-test): change cache path

.github/workflows/actions-tagger.yaml
As explained in https://github.com/autowarefoundation/autoware-github-actions/pull/38#issue-1118683293, I'll add [Actions-R-Us/actions-tagger](https://github.com/Actions-R-Us/actions-tagger).
=> ci: add actions-tagger.yaml

generate-changelog/action.yaml, sync-branches/action.yaml
Remove `CHANGELOG.md` in `generate-changelog` to prevent unintended commits.
https://github.com/kenji-miyake/autoware-github-actions/pull/16/commits/b84f77ec8930bca61ea9b72f66ffdfdbba1ac9d6
=> fix(generate-changelog): remove CHANGELOG.md

.github/workflows/github-release.yaml, cliff.toml
It is useful if we can automatically create or prepare releases by publishing tags.
Also, since this is a repository for GitHub Actions, it's good to provide tags such as `v1`, `v2`, etc.
https://github.com/actions/toolkit/blob/master/docs/action-versioning.md#versioning
[Actions-R-Us/actions-tagger](https://github.com/Actions-R-Us/actions-tagger) can automate this.
I've tested this in this repository.
https://github.com/kenji-miyake/test-git-cliff-release
=> ci: add GitHub release workflow

clang-tidy/action.yaml, colcon-build-and-test/action.yaml, colcon-build/action.yaml, colcon-test/action.yaml
Signed-off-by: Takagi, Isamu <isamu.takagi@tier4.jp>
Skip the `rosdep install` of unnecessary packages.
=> feat: skip the rosdep install of unnecessary packages

spell-check/action.yaml
`dist/` is commonly used as the auto-generated files of JavaScript/TypeScript actions.
https://github.com/streetsidesoftware/cspell-action#usage
=> fix(spell-check): ignore dist/

spell-check/action.yaml
Reverts autowarefoundation/autoware-github-actions#70
Ignored in https://github.com/tier4/autoware-spell-check-dict/pull/207.
=> revert(spell-check): ignore dist/

clang-tidy/action.yaml
https://github.com/platisd/clang-tidy-pr-comments
- Useful features
- Simple interface of `fixes.yaml`
Alternative apps:
- https://github.com/ZedThree/clang-tidy-review
- Probably no interface for `fixes.yaml`
=> feat(clang-tidy): export files for clang-tidy-pr-comments

clang-tidy/action.yaml, colcon-build-and-test/action.yaml, colcon-build/action.yaml, colcon-test/action.yaml
This PR is to fix the ci error of build and test workflow as below.
https://github.com/tier4/jetson_camera_trigger/runs/5176664994?check_suite_focus=true
This is my local test result.
```
~/workspace/sandbox_ws/src/jetson_camera_trigger ros2
❯ mkdir dependency_ws
~/workspace/sandbox_ws/src/jetson_camera_trigger ros2
❯ vcs import dependency_ws < build_depends.repos
=== dependency_ws/core/common (git) ===
Cloning into '.'...
~/workspace/sandbox_ws/src/jetson_camera_trigger ros2
❯ colcon list -p --packages-above-and-dependencies jetson_camera_trigger
.
~/workspace/sandbox_ws/src/jetson_camera_trigger ros2
❯ rosdep install --from-paths . --ignore-src -y
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
jetson_camera_trigger: Cannot locate …
```
=> fix: add base paths to resolve rosdep dependency

colcon-build/action.yaml, colcon-test/action.yaml
Resolves: https://github.com/autowarefoundation/autoware.universe/issues/403
This is a change to match the `colcon-build` and `colcon-test` caches to account for OS and CPU architecture.
=> fix(colcon-build,colcon-test): match build and test cache

colcon-build-and-test/action.yaml, colcon-test/action.yaml
Create a PR to fix the following error.
A possible solution is to run the tests in sequential order.
https://github.com/autowarefoundation/autoware.universe/runs/5283234004?check_suite_focus=true
=> feat(colcon-test): use sequential executor

.github/workflows/github-release.yaml
Resolves #82
Same as https://github.com/tier4/pre-commit-hooks-ros/pull/38.
=> ci(github-release): use env to escape double quotes

cliff.toml
To ignore tags like `v0`, `v1`, etc.
=> chore(cliff.toml): fix tag_pattern

.github/workflows/test-composite-actions.yaml
=> test: fix URL of .clang-tidy

deploy-docs/action.yaml
As a follow-up to #93, added options.
https://github.com/jimporter/mike#building-your-docs
> If [version] already exists, this command will also update all of the pre-existing aliases for it. Normally, if an alias specified on the command line is already associated with another version, this will return an error. If you do want to move an alias from another version to this version (e.g. when releasing a new version and updating the latest alias to point to this new version), you can pass -u/--update-aliases to allow this.
> 
> By default, aliases create a simple HTML redirect to the real version of the docs; to create a copy of the docs for each alias, you can pass --no-redirect.
=> fix(deploy-docs): add `--update-aliases` and `--no-redirect` to `mike alias`

deploy-docs/mkdocs-requirements.txt
https://github.com/fralau/mkdocs_macros_plugin/
For example, using `{{ config.site_url }}` is useful considering fork repositories.
=> feat(deploy-docs): add mkdocs-macros-plugin

delete-closed-pr-docs/action.yaml
Related #96
The problem is that `delete-closed-pr-docs` cannot ignore `latest` tag.
To resolve this, I have modified the script to https://github.com/autowarefoundation/autoware-github-actions/issues/96#issuecomment-1061292507
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-re …
=> fix(delete-closed-pr-docs): ignore latest tag on pull_request

.github/dependabot.yaml
Added `dependabot` settings for composite actions.
=> ci: add dependabot for composite actions

delete-closed-pr-docs/action.yaml
Closes #79 
(The description is in issue.)
=> fix(delete-closed-pr-docs): remove PR directory when there is no corresponding PR

delete-closed-pr-docs/action.yaml
Closes #79 
Follow-up PR for #79 
I have tested this change on my fork repo:
https://github.com/KeisukeShima/autoware.universe/runs/5638647412?check_suite_focus=true
=> fix(delete-closed-pr-docs): ignore errors

deploy-docs/action.yaml
It seems `mike alias` doesn't alias images, which is inconvenient for us.
So I changed it to copy all files.
It will increase the file size, but I assume it's not a big problem.
=> feat(deploy-docs): don't use mike alias for latest

sync-files/README.md, sync-files/action.yaml
Signed-off-by: h-ohta <hiroki.ota@tier4.jp>
- Add `Enable auto merge` as a reference 
https://github.com/autowarefoundation/autoware-github-actions/blob/main/sync-branches/action.yaml#L102-L108
- Actually, we also have to set `auto-merge-method` variables` to any in order to enable auto merge.
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-r …
=> feat(sync-files): enable auto merge

.github/workflows/semantic-pull-request.yaml
Added the `ignoreLabels` option to resolve some inconvenience when there is only one commit.
Related PRs:
- https://github.com/amannn/action-semantic-pull-request/pull/174
- https://github.com/autowarefoundation/autoware/pull/167
=> feat(semantic-pull-request): add ignoreLabels

.github/workflows/test-composite-actions.yaml, get-modified-packages/README.md, get-modified-packages/action.yaml
`github.base_ref` is only accessible from `pull_request` events.
https://docs.github.com/en/actions/learn-github-actions/contexts
Therefore, it can't be tested now.
https://github.com/autowarefoundation/autoware-github-actions/runs/6070315459?check_suite_focus=true#step:10:9
To resolve this, I made the `base-branch` an input. …
=> feat(get-modified-packages): make base-branch an input in order to be testable

.github/workflows/test-composite-actions.yaml
It seems can't be used in scheduled jobs. :thinking: 
https://github.com/autowarefoundation/autoware-github-actions/runs/6185500582?check_suite_focus=true#step:10:3
=> ci(test-composite-actions): relpace default_branch with main

deploy-docs/mkdocs-requirements.txt
mdx_unimoji is deprecated and it should be deleted
https://github.com/autowarefoundation/autoware-github-actions/issues/145
If you use emoji, you can use https://github.com/facelessuser/pymdown-extensions for example, which is automatically installed with deploy-docs/mkdocs-requirements.txt
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-requ …
=> fix(deploy-docs): remove mdx_unimoji

sync-files/README.md, sync-files/action.yaml, sync-files/parse_config.py
It's useful if we can run commands before/after copying files.
https://github.com/chmln/sd is added because it's more useful than pure `sed`.
I've tested this in https://github.com/kenji-miyake/autoware-github-actions/pull/43.
The CI log is https://github.com/kenji-miyake/autoware-github-actions/runs/6427565108?check_suite_focus=true.
Sample settings:
```yaml
- repository: autowarefoundation/autoware
files:
- source: .pre-commit-config.yaml
post-commands: |
sd -f ms "[^\n]*shellcheck-py\n.*?\n\n" "" {dest}
```
After all checkboxes are checked, anyone who has write access can merge the …
=> feat(sync-files): add pre-command and post-command

sync-branches/action.yaml
It causes an error when there is a branch named samely in `origin` and `sync-target`.
https://github.com/tier4/autoware_launch/runs/6540294177?check_suite_focus=true#step:3:981
```
/usr/bin/git checkout --progress sync-awf-latest --
hint: If you meant to check out a remote tracking branch on, e.g. 'origin',
hint: you can do so by fully qualifying the name with the --track option:
hint: 
hint:     git checkout --track origin/<name>
hint: 
hint: If you'd like to always have checkouts of an ambiguous <name> prefer
hint: one remote, e.g. the 'origin' remote, consider setting
hint: checkout.defaultRemote=origin in your config.
fatal: 'sync-awf-latest' matched multiple (2) remote tracking branches
```
With this PR, it's fixed.
https://github.com/tier4/autoware_launch/runs/6542017596?check_suite_ …
=> fix(sync-branches): remove git remote "sync-target" after using the data

clang-tidy/action.yaml, colcon-build/action.yaml, colcon-test/action.yaml
To support multi distros, I'd like to add `rosdistro` to the cache key.
=> fix(colcon-build, colcon-test, clang-tidy): add rosdistro to cache key

remove-exec-depend/action.yaml
Resolves #159.
Also, the order of `0-9` and `_` was flipped for visibility.
My test result is here: https://github.com/autowarefoundation/autoware-github-actions/issues/159#issuecomment-1149189998
=> fix(remove-exec-depend): add `-` to the pattern of package names

deploy-docs/README.md, deploy-docs/action.yaml
Signed-off-by: Takayuki AKAMINE <takayuki.akamine@tier4.jp>
I'd like to update `deploy-docs` to give customized `mkdocs-requirements.txt`. The default requirements file `${GITHUB_ACTION_PATH}/mkdocs-requirements.txt}` will be used if users don't describe any input file.
I've tested this change with two patterns; using default `mkdocs-requirements.txt` and using customized one.
- Default requirements.txt : `${GITHUB_ACTION_PATH}/mkdocs-requirements.txt}` (like [CARET_doc](https://github.com/tier4/CARET_doc/blob/73768b43bbc555d41795579901a8005d78e4e5a3/.github/workflows/deploy-docs.yaml#L37-L41))
- [`pip3 install`](https://github.com/tier4/CARET_doc/runs/6806496213?check_suite_focus=true#step:3:15) command was executed with `${GITHUB_ACTION_PATH}/mkdocs-requirements.txt}`
- All packages are …
=> feat(deploy-docs): add new input variable to select mkdocs-requirements

deploy-docs/create-doc-comment.sh
It didn't work with the files named like `index.ja.md`.
Before:
After:
=> fix(deploy-docs): support i18n files

sync-files/action.yaml
- To calculate the diff correctly, run pre-commands before if-condition.
- Remove `|| true` because it isn't planned to be used for now.
- I think using `{dest}` in `pre-command` is a super-advanced use case.
- Fix comments.
=> fix(sync-files): run pre-commands before if-condition

.github/workflows/semantic-pull-request.yaml
An alternative feature is officially supported.
https://github.blog/changelog/2022-05-11-default-to-pr-titles-for-squash-merge-commit-messages/
https://github.com/github/feedback/discussions/16271
However, I think we have to instead check if the option is enabled.
So I'll make this a draft until that.
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributin …
=> feat(semantic-pull-request): disable validateSingleCommitMatchesPrTitle

clang-tidy/action.yaml
Without this, it causes the following error due to the `-fopenmp` option.
```
/usr/include/eigen3/Eigen/Core:70:10: error: 'omp.h' file not found [clang-diagnostic-error]
#include <omp.h>
```
> LLVM OpenMP runtime - dev package
https://packages.ubuntu.com/jammy/libomp-dev
=> fix(clang-tidy): install libomp-dev to prevent clang-diagnostic-error

spell-check/README.md, spell-check/action.yaml
It is useful if we can use local dictionaries that are in the target repository.
Users can define repository-specific words.
=> feat(spell-check): support local dictionary

clang-tidy/README.md, clang-tidy/action.yaml
Currently, many files are checked in the workflow, but it's too slow.
So I'd like to support the `target-files` input to limit the target files to be analyzed.
https://github.com/autowarefoundation/autoware.universe/runs/8107659485?check_suite_focus=true#step:6:252
=> ci(clang-tidy): support target files input

spell-check/README.md, spell-check/action.yaml
It is useful if we can add dict packages.
Users need to import dict packages in their `.cspell.json`.
```jsonc
// .cspell.json
{
...
"import": ["@tier4/cspell-dicts/cmake/cspell-ext.json"],
...
}
```
Related links: 
- https://github.com/tier4/cspell-dicts
- https://github.com/streetsidesoftware/cspell-dicts
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contr …
=> feat(spell-check): support installing dict packages

.github/workflows/semantic-pull-request.yaml
Similar to https://github.com/autowarefoundation/autoware-github-actions/pull/148, I think we can also remove `validateSingleCommit` now. I just forgot to remove it.
`action-semantic-pull-request` ensures that the PR title is semantic.
https://github.com/amannn/action-semantic-pull-request/blob/4682b170e7c31dfbef288e994fe07853755229b4/src/index.js#L67
With this PR, we can remove this part in the pull request guidelines.
https://github.com/autowarefoundation/autoware-documentation/blob/af6c4d1b2c0747aa93f5c50899fa0c07e93b6d21/docs/contributing/pull-request-guidelines/index.md?plain=1#L74-L76
The PR author **must** check the checkboxes below before …
=> feat(semantic-pull-request): disable validateSingleCommit

update-codeowners-from-packages/action.yaml
See https://github.com/autowarefoundation/autoware.universe/pull/1788#discussion_r970224629.
=> fix(update-codeowners-from-packages): use "**" instead of "*"

update-codeowners-from-packages/action.yaml
Fixes https://github.com/autowarefoundation/autoware_common/pull/111#issuecomment-1254377719.
=> fix(update-codeowners-from-packages): sort the order of packages

clang-tidy/README.md, clang-tidy/action.yaml, colcon-build/README.md, colcon-build/action.yaml
`Release` can overlook some mistakes.
Related: https://github.com/autowarefoundation/autoware.universe/issues/1959
=> feat(clang-tidy, colcon-build): make CMAKE_BUILD_TYPE optional

clang-tidy/action.yaml, colcon-build/action.yaml, colcon-test/action.yaml
Probably resolves https://github.com/autowarefoundation/autoware.universe/issues/1959#issuecomment-1260731484.
=> fix(clang-tidy, colcon-build, colcon-test): add cmake-build-type to cache key

clang-tidy/action.yaml
To reflect the result of the `clang-tidy` command, we need to set the exit code correctly.
Currently, it's ignored.
We need to fix this condition as well: https://github.com/autowarefoundation/autoware_common/blob/efd676c788735bc74889b50558536980230b0b9d/.github/workflows/clang-tidy-pr-comments.yaml#L12
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contribut …
=> fix(clang-tidy): mark the workflow as failed if the fixes.yaml file exists

spell-check/README.md, spell-check/action.yaml
Add incremental-files-only option in spell-check workflow to check all files
=> feat(spell-check): add incremental-files-only option

update-codeowners-from-packages/README.md, update-codeowners-from-packages/action.yaml
@xmfcx wants global codeowners to bypass reviews safely.
Currently, bypassing reviews isn't supported as we desire.
=> feat(update-codeowners-from-packages): support global codeowners

pre-commit/action.yaml
Signed-off-by: Tomohito Ando <tomohito.ando@tier4.jp>
Fixed workflow stopping when it failed.
For example, if there are clang-format failure and cpplint failure, workflow stops without fixing clang-format errors.
=> feat: prevent a workflow from stopping when pre-commit fails

.pre-commit-config.yaml, pre-commit/action.yaml
Signed-off-by: Tomohito Ando <tomohito.ando@tier4.jp>
Used [pre-commit action](https://github.com/pre-commit/action) and [git-auto-commit action](https://github.com/stefanzweifel/git-auto-commit-action) instead of running scripts.
related PR
- https://github.com/autowarefoundation/autoware-github-actions/pull/197
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main …
=> refactor(pre-commit): use actions instead of scripts

clang-tidy/action.yaml, colcon-build/action.yaml, colcon-test/action.yaml
- add argument `include-eol-distros`
=> feat(clang-tidy, colcon-build, colcon-test): add include-eol-distros

delete-closed-pr-docs/action.yaml, deploy-docs/action.yaml
I'd like to remove `--rebase` arguments used for the `mike` command.
[`mike`](https://github.com/jimporter/mike) no longer supports the argument `--rebase` according to [its change log](https://github.com/jimporter/mike/commit/872f72def32f588908f8251fe512189e0c41f4e2).
I have tested this change in [CARET_doc] repository with applying this change ([link](https://github.com/tier4/CARET_doc/commit/4427ff5d3dc141724d9b15552f6580f0d1a7ec74)).
I have checked that this PR works properly at https://github.com/tier4/CARET_doc/pull/165. 
`deploy-docs` action ran successfully at https://github.com/tier4/CARET_doc/actions/runs/4339600632/jobs/7577349374
`delete-closed-pr-docs` action ran at https://github.com/tier4/CARET_doc/actions/runs/4339649620/jobs/7577438685#step:3:205
The PR author **must** …
=> fix(deploy-docs, delete-closed-pr-docs): remove staled argument `--rebase` of mike

pre-commit-autoupdate/README.md, sync-branches/README.md, sync-files/README.md, update-codeowners-from-packages/README.md
It was replaced by GitHub CLI.
Related:
- https://github.com/autowarefoundation/autoware-github-actions/pull/212
- https://github.com/autowarefoundation/autoware-github-actions/pull/213
- https://github.com/autowarefoundation/autoware-github-actions/pull/214
- https://github.com/autowarefoundation/autoware-github-actions/pull/216
=> docs: remove peter-evans/enable-pull-request-automerge

delete-closed-pr-docs/action.yaml
A fix for https://github.com/autowarefoundation/autoware-github-actions/pull/218.
The output of `mike list` is multiline.
```console
❯ mike list | grep -oP "pr-\w+"
pr-321
pr-317
pr-312
pr-290
pr-287
pr-279
pr-278
pr-276
pr-220
pr-195
pr-172
pr-82
```
Due to that, `echo "docs-versions=$(mike list | grep -oP "pr-\w+")" >> $GITHUB_OUTPUT` fails:
```
Run echo "site_name: dummy" > mkdocs.yaml
Error: Unable to process file command 'output' successfully.
Error: Invalid format 'pr-335'
```
Previously, it was automatically converted into space-deliminated.
To be the same output as the previous one, added `tr` and `sed`:
```console
❯ mike list | grep -oP "pr-\w+" | tr '\n' ' ' | sed 's/\s*$//'
pr-321 pr-317 pr-312 pr-290 pr-287 pr-279 pr-278 pr-276 pr-220 pr-195 pr-172 pr-82⏎
```
=> fix(delete-closed-pr-docs): fix incorrect multiline output

pre-commit/README.md, pre-commit/action.yaml
I guess the current usage is wrong because `pre-commit/action` doesn't have the `token` input: https://github.com/pre-commit/action/blob/646c83fcd040023954eafda54b4db0192ce70507/action.yml#L3
This workflow was added in https://github.com/autowarefoundation/autoware_core_universe_prototype/pull/179.
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/p …
=> fix(pre-commit): fix token input

pre-commit/README.md, pre-commit/action.yaml
Add `base-branch` input to pre-commit action for differential check.
None
https://github.com/isamu-takagi/github-actions-sandbox/pull/1
It needs to add `fetch-depth: 0` to checkout action.
=> feat(pre-commit): add base-branch for differential execution

README.md, json-schema-check/README.md, json-schema-check/action.yaml
Create a new action, where the goal is to check the compliance of configuration files against their Schema template.
Leveraging the check-jsonschema CLI tool.
It can then be used in autoware.universe and autoware.core.
Implements https://github.com/autowarefoundation/autoware-github-actions/issues/232
I haven't tested the deployment as a dedicated Github action in a separate repository, but I tested the specific commands in CI:
Checked that it passed on correct configuration files at https://github.com/ambroise-arm/autoware.universe/actions/runs/5354465514
Checked that it failed on wrong configuration files at https://github.com/ambroise-arm/autoware.universe/actions/runs/5322522827
I will have a follow up PR to autoware.universe to make use of this.
The PR author **must** check the …
=> feat(json-schema-check): add new action

generate-changelog/README.md, generate-changelog/action.yaml
This PR enables to generate JSON changelog.
It won't change the current generate-changelog behavior.
Note that "Show result" is only for markdown changelog, not for JSON changelog.
This is because when we create a large JSON changelog and try to `echo` it, it says "Argument list too long" and CI failed
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributi …
=> feat(generate-chnagelog): add generate-changelog-json

colcon-build/action.yaml
This PR disables access to internet with `unshare` so that we make sure that packages do not download any artifacts during the build step.
=> build: disable internet access during the build step

pre-commit-autoupdate/action.yaml, sync-branches/action.yaml, sync-files/action.yaml, update-codeowners-from-packages/action.yaml
The `peter-evans/create-pull-request` action uses `github.actor` as the commit author by default.
For scheduled actions, this is the user who last modified the cron section of the workflow.
Therefore, set the author to `github-actions` to indicate that it was committed by the action.
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/ma …
=> feat: set author to create-pull-request action

sync-files/README.md, sync-files/parse_config.py
A repository has been created by https://github.com/autowarefoundation/autoware/issues/4058 that will be the source of sync-file. In this repository, files are placed under an arbitrary directory, so add an option `source-dir` to specify the source directory.
Check settings and its result here.
- https://github.com/isamu-takagi/github-actions-sandbox/blob/sync-file/.github/sync-files.yaml
- https://github.com/isamu-takagi/github-actions-sandbox/pull/5
[contribution guidelines]: …
=> feat(sync-files): add source-dir option

json-schema-check/action.yaml
The goal is to allow one schema file per node in a package. And to allow several configuration files per schema. The schema files have to follow a NODE_NAME.schema.json naming convention and the configuration files have to follow a NODE_NAME*.param.yaml naming convention.
Implements https://github.com/autowarefoundation/autoware-github-actions/issues/232#issuecomment-1746971463
**Depends on https://github.com/autowarefoundation/autoware.universe/pull/5798 in order to pass on the autoware.universe codebase**
Command run locally on autoware.universe with the changes in the PR above. …
=> feat(json-schema-check): allow for several schema files per package

json-schema-check/action.yaml, json-schema-check/validate_json_schemas.py
- This PR makes it easier to find the source of errors in the checks.
- Also makes it more clear on what exact files are checked against which exact schemas.
- Also converts the bash one-liner to a python script for maintainability.
Temporarily created a tag named `vTempTestJson` to test it from Universe.
- https://github.com/autowarefoundation/autoware.universe/actions/runs/7979187696/job/21793290925#step:3:42
- https://github.com/autowarefoundation/autoware.universe/actions/runs/7981506848/job/21793322599#step:3:43
Colorful outputs!
After all checkboxes are checked, anyone who has …
=> ci(json-schema-check): improve readibility and output helpful debug info

update-codeowners-from-packages/action.yaml
modify the order to update CODEOWNER to apply manually defined CODEOWNERS first.
=> fix(update-codeowners-from-packages): add manual CODEOWNERS after package CODEOWNERS

json-schema-check/validate_json_schemas.py
Currently, `json-schema-check` considers only specific files match: `schema/<schema_cfg_name>.schema.json` and `config/<schema_cfg_name>.param.yaml`. For packages with many config files, the config directory structure may differ. Even though the files follow naming convention, the sub directories are not taken into account. This small change in pull request adds following naming convention: `schema/<schema_cfg_name>.schema.json` and `config/<namespace>/<schema_cfg_name>.param.yaml`.
Checked locally with CI script few test cases, **success** stands for `Validating ...`  and **fail** stands for `No configuration files found for schema ...` or schema was not found.
1. Expected success.
```
<package_name>
|
|—— schema
|     |—— <schema_cfg_name>.schema.json
|
|—— config
|     |—— …
```
=> ci(json-schema-check): allow nested config paths

sync-files/action.yaml
Added ` --depth 1 ` to the `git clone` operation, performing a shallow clone, avoiding downloading entire history and branches of a repository.
It doesn't use anything more, so it should be safe.
Assume the following `sync-files.yaml` configuration:
```yaml
- repository: autowarefoundation/autoware_common
files:
- source: .github/workflows/build-and-test.yaml
dest: .github/workflows/build-and-test-daily.yaml
- source: .github/workflows/build-and-test.yaml
dest: .github/workflows/build-and-test-daily-arm64.yaml
```
It wants to copy from a source file into multiple destinations.
But when we run it with the existing configuration, it only generates the `dest: .github/workflows/build-and-test-daily-arm64.yaml` file. And completely ignores the first destination.
<details>
<summary>🖱️Click here …
=> feat(sync-files): allow multiple destinations and speed up clone

sync-files/action.yaml
Instead of modifying the source file in place, first copy it to a temp location with [mktemp](https://www.gnu.org/software/autogen/mktemp.html), then do all the modifications and copy to dest path as usual.
Currently it modifies the source files in place.
If multiple versions are to be created from the same source file, it will modify them multiple times, breaking files.
Tested with the temporary `v-test-sync-files` tag. By calling it from:
- https://github.com/autowarefoundation/autoware.universe/pull/7340
After all checkboxes are checked, anyone who has write access …
=> fix(sync-files): keep original source file intact

get-modified-packages/README.md, get-modified-packages/action.yaml, get-modified-packages/get-modified-packages.sh
Continuation from:
- https://github.com/autowarefoundation/autoware.universe/pull/7408
- Renaming the input parameter name from `base-branch` to `base-ref`. (Mostly it defaults to `main`)
- I think it is not used anywhere.
- But we might use it for `merge_group` triggers in the future
- It will run: `git fetch origin ${{ inputs.base-ref }}` to make sure it has common merge-base commit to get diffs
- And now it is possible to only fetch the necessary commits instead of entire history of the repository. (For universe it allows time saving from about 2m30s to 6s)
- Separate the `get-modified-packages` action into 2 steps so it will report if it fails
- Also exit with failure on the sh script.
- `set -e` is removed from the script because it is set by default on github actions.
It fails on …
=> feat(get-modified-packages): support retrieving diffs without fetching all

.github/workflows/make-sure-label-is-present.yaml
- Right now, if we add multiple labels to a PR, only one of them works.
- This action currently checks only if the newly added label is the correct one.
- But it should instead, check if the required label is in the labels list.
- It is much simpler.
Being tested with:
- https://github.com/autowarefoundation/autoware_common/pull/250 …
=> feat(make-sure-label-is-present): new workflow

clang-tidy/action.yaml, colcon-build/action.yaml, colcon-test/action.yaml
This PR:
- Removes `restore-build-files` step from the `colcon-test`
- It harbored a bug: `inputs.cmake-build-type` was forgotten to be defined on the action inputs, it was empty all the time and cached(saved and restored) unnecessary stuff.
- This was added here because they thought `colcon-build` and `colcon-test` tasks could run on different jobs (different machines).
- But it was unnecessary and everywhere, we use it like `build-and-test-x` because it is more efficient (and fast) to run them on the same machine.
- Right now, this is also creating a bug because of the wrong cache names. Example bug:
- noncuda and cuda `build-and-test-differential` jobs have the same cache key
- these 2 jobs run in parallel
- noncuda finishes first and populates the cache (with colcon-build ending)
- …
=> fix: caching strategies of colcon-build/test and clang-tidy

colcon-test/README.md, colcon-test/action.yaml
Explained in detail in:
- https://github.com/autowarefoundation/autoware.universe/issues/7733
Being tested by:
- https://github.com/autowarefoundation/autoware.universe/pull/7731
=> fix(colcon-test): remove label-regex filter

clang-tidy/action.yaml
**Related PR:**
- https://github.com/autowarefoundation/autoware.universe/pull/7729#issuecomment-2195994727
The current clang-tidy fails when there exists a `fixes.yaml`.
It leads to the CI failure even when clang-tidy reports only warnings.
I have changed it so that the CI fails only when it reports errors.
@xmfcx 
The way I used whether clang-tidy reports an errors is the following:
```
if [ -n "$(grep ": error:" /tmp/clang-tidy-result/report.txt)" ];
```
I'm not sure there is a better way, so please review it carefully. Thank you in advance!
After …
=> fix(clang-tidy): make clang-tidy workflow fail only when it reports errors

colcon-test/action.yaml
When displaying coverage, I believe it's generally unnecessary to include the coverage of the test files themselves. Therefore, in this PR, I've configured the settings to exclude them.
=> chore(colcon-test): ignore test directory in colcon lcov-result

colcon-build/README.md, colcon-build/action.yaml
`nice` is part of GNU coreutils, let's you run a program with modified scheduling priority.
Comes bundled in the our Ubuntu containers.
This PR aims to utilize it to prevent `colcon build` from overusing the runner resources.
[man page](https://manpages.ubuntu.com/manpages/jammy/en/man1/nice.1.html)
> Run COMMAND with an adjusted niceness, which affects process scheduling.  With no COMMAND,
> print the current niceness.  Niceness  values  range  from  **-20**  (most  favorable  to  the
> process) to **19** (least favorable to the process).
I set the default to be 19 in this PR.
Original default was 10.
Related PR:
- https://github.com/autowarefoundation/autoware.universe/pull/8498
Failure example for a runner due to over-usage of a machine during colcon build:
- …
=> feat(colcon-build): use nice command to not overuse resources

colcon-build/README.md, colcon-build/action.yaml
Follow up from:
- https://github.com/autowarefoundation/autoware-github-actions/pull/308
Related:
- https://github.com/autowarefoundation/autoware.universe/pull/8498
=> feat(colcon-build): enable cpu resource control

colcon-build/README.md, colcon-build/action.yaml
- https://github.com/autowarefoundation/autoware-github-actions/pull/309
This PR tries to limit the number of CPUs used by the runner.
But instead of using the usual `--parallel-workers 3` or `MAKEFLAGS=-j4` that limit the ways we can pick how many cores are assigned, we can also make use of `taskset --cpu-list 0-4 colcon build ...` which will use first 5 cores.
Since we already added the `nice-command` as a pre-command for the colcon build, let's generalize it so we can use it with this purpose as well.
Related:
- https://github.com/autowarefoundation/autoware.universe/pull/8498
- https://github.com/autowarefoundation/autoware.universe/actions/runs/10468690696/job/28990143275?pr=8498#step:13:310
The …
=> refactor(colcon-build): nice-command to build-pre-command

.github/workflows/test-composite-actions.yaml
Fix not to use outdated image in the workflow.
Not provided.
(I'll put after tests as this PR needs to run the workflows)
No interface change exists in this PR
No change exists in this PR.
No change exists in this PR.
The failing workflow ```test-composite-actions``` will succeed.
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidel …
=> fix(test-composite-actions): use newer ghcr image

deploy-docs/mkdocs-requirements.txt
- https://github.com/autowarefoundation/autoware-documentation/pull/615
[failed](https://github.com/autowarefoundation/autoware-documentation/actions/runs/10936828636/job/30373333905?pr=615#step:3:417) today. 
```
error: No module named 'pathspec'
Error: Process completed with exit code 1.
```
This PR attempts to fix this. (Not sure why it happened)
Will test in:
- https://github.com/autowarefoundation/autoware-documentation/pull/615
to test this temporarily.
[contribution guidelines]: …
=> build(deploy-docs): add pathspec as dependency

create-prs-to-update-vcs-repositories/create_prs_to_update_vcs_repositories.py
This PR fixes so the version update PR contains the `git diff` of the target repository.
Currently the version update PR contains poor information in its description [as this](https://github.com/autowarefoundation/autoware/pull/5304) and this makes the review difficult.
[Discussion for feature improvement](https://github.com/orgs/autowarefoundation/discussions/5305)
~~After the PR author finishes their tests, this will be updated.~~
I verified that a PR is created as [this](https://github.com/autowarefoundation/autoware_dummy_repository/pull/112). The PR contains the `git diff` so I believe this is enough as tests.
Currently, the version update PR does not contain `git diff` and the reviewer needs to go to the target repository by themselves. This PR reduces such the additional task.
No …
=> feat: attach `git diff` in the PR description

clang-tidy/action.yaml
Excluded `test` and `examples` directories from clang-tidy checks.
They are not necessary to be analyzed.
Checked locally whether the new command can really exclude those directories.
=> fix(clang-tidy): exclude test and example directories from clang-tidy check

clang-tidy/action.yaml
This PR introduces support for ignoring specific files in `clang-tidy`.  
To achieve this, you can create a `.clang-tidy-ignore` file under your project directory and list file paths or regular expressions for the files you wish to ignore, as shown below:
```
*/examples/*
perception/**
```
Additionally, this PR includes minor changes.
1. Use `run-clang-tidy` instead of `clang-tidy`.  
- `run-clang-tidy` allows for parallel execution of `clang-tidy`.
2. Change the report file suffix from `.txt` to `.log`.  
- Most editors (e.g., VS Code) can colorize log files, enhancing their readability.  
- https://github.com/autowarefoundation/autoware.universe/pull/9498
Tested in [this Action](https://github.com/autowarefoundation/autoware.universe/actions/runs/12063019141/job/33639712216).
Not …
=> feat(clang-tidy): introducing .clang-tidy-ignore

clang-tidy/action.yaml
Refactored error determination for CI when using run-clang-tidy because it was not working properly.
Instead of looking for errors in the log with `grep`, change to determine them by `exit_code` in run-clang-tidy.
Tested on [this PR](https://github.com/autowarefoundation/autoware.universe/pull/9593).
- [Log of success](https://github.com/autowarefoundation/autoware.universe/actions/runs/12249643124/job/34172511311?pr=9593)
- [Log of Failure](https://github.com/autowarefoundation/autoware.universe/actions/runs/12249643124/job/34171942667?pr=9593)
None.
None.
=> feat(clang-tidy): determine error using exit_code

create-prs-to-update-vcs-repositories/create_prs_to_update_vcs_repositories.py
Fix a bug that the newest tag is not applied for the created PRs.
The tests are performed by using [this repository](https://github.com/autowarefoundation/autoware_dummy_repository). The used workflow is provided [here](https://github.com/autowarefoundation/autoware_dummy_repository/blob/9c61c2fc504dba0437d368239eb029dcaa959bea/.github/workflows/create-version-update-pr.yaml). Also you can see the result of the workflow from [here](https://github.com/autowarefoundation/autoware_dummy_repository/actions/runs/12410007506).
We verified the following test is passed:
Condition:
- Fix the current version to be `0.0.1`
- On the [target repository](https://github.com/tier4/scenario_simulator_v2), there are tags like:
- `7.3.3`, `7.3.2`, ... , `0.9.0`, `0.8.0`, ... `0.1.1`, `0.1.0`, and `0.0.1` …
=> fix: bugs that the latest tag is not parsed

.github/workflows/require-label.yaml
🤔 We have [make-sure-label-is-present.yaml](https://github.com/autowarefoundation/autoware-github-actions/blob/main/.github/workflows/make-sure-label-is-present.yaml) but it skips when it cannot find the label and let's the remaining actions decide what to do with the result. Because it doesn't fail, it skips the remaining workflows.
🫤 We also have [prevent-no-label-execution.yaml](https://github.com/autowarefoundation/autoware-github-actions/blob/main/.github/workflows/prevent-no-label-execution.yaml) which has the identical behavior. But this one is only here for legacy reasons, it can get confused when multiple labels are added at the same time.
So we needed a workflow that actually fails when the input label is not present.
`require-label` workflow does just that. It's a slightly …
=> ci(require-label): add new reusable workflow

.github/workflows/require-label.yaml
The action was not returning the result due to a mistake in the modified line.
It now refers to the step correctly and returns "true" if successful.
- Description is also updated.
- Unused variable at the failed step is removed too.
- https://docs.github.com/en/actions/sharing-automations/reusing-workflows#using-outputs-from-a-reusable-workflow
> ```yaml
> name: Reusable workflow
> 
> on:
>   workflow_call:
>     # Map the workflow outputs to job outputs
>     outputs:
>       firstword:
>         description: "The first output string"
>         value: ${{ jobs.example_job.outputs.output1 }}
>       secondword:
>         description: "The second output string"
>         value: ${{ jobs.example_job.outputs.output2 }}
> 
> jobs:
>   example_job:
>     name: Generate output
>     runs-on: …
```
=> fix(require-label): output the result

deploy-docs/mkdocs-requirements.txt
This will fix version for plantuml-markdown package installed through pip.
The latest version is 3.11.0, but it fails with the new PRs: https://github.com/autowarefoundation/autoware-documentation/actions/runs/13175923845/job/36775082449?pr=644
This specifies the version for plantuml-markdown to use the older version 3.10.4 which was working before. 
Tested with this action:
https://github.com/mitsudome-r/autoware-documentation/actions/runs/13181082692/job/36791752054
[contribution …
=> fix(deploy-docs): fix version for plantuml-markdown

colcon-build/action.yaml
Sets it empty, I probably forgot to remove it before.
Shouldn't break any existing functionality.
Related:
- https://github.com/autowarefoundation/autoware.universe/pull/10198#discussion_r1970847996
=> feat(colcon-build): set the default pre-command to empty

.github/workflows/test-composite-actions.yaml
The `autoware:latest-universe-devel` image tag is no longer available. This PR fixes the tag.
https://github.com/autowarefoundation/autoware-github-actions/actions/runs/13698027694/job/38304826018?pr=338
=> fix(test-composite-actions): update `autoware` image tag

colcon-build/action.yaml
In the current `autoware` images, the build artifacts of Autoware are saved under `/opt/autoware`. 
https://github.com/autowarefoundation/autoware/blob/main/docker/Dockerfile#L158
https://github.com/autowarefoundation/autoware/blob/main/docker/scripts/build_and_clean.sh#L15
Therefore, in order to reference these artifacts, it is necessary to source `/opt/autoware/setup.sh`.
This PR makes that change. By doing so, it is expected to reduce unnecessary repository references in `build_depends.repos` and shorten the build time.
- https://github.com/youtalk/autoware.core/pull/2
- https://github.com/youtalk/autoware-github-actions/pull/2
- https://github.com/youtalk/autoware.core/actions/runs/13694329844/job/38293387944?pr=2
The PR author **must** check the checkboxes below when …
=> feat(colcon-build): source /opt/autoware/setup.sh if exists

clang-tidy/action.yaml, colcon-build/README.md, colcon-build/action.yaml, colcon-test/README.md, colcon-test/action.yaml
This PR adds a `packages-above-repos` argument to colcon-build, colcon-test and clang-tidy github actions.
This change is for the following PR, which describes the background.
https://github.com/autowarefoundation/autoware.universe/pull/9854
See https://github.com/autowarefoundation/autoware.universe/pull/9854 …
=> feat(colcon-build, colcon-test, clang-tidy): add packages-above-repos argument

colcon-test/README.md, colcon-test/action.yaml
Sometimes we want to exclude certain packages from testing, because they are vendor packages and not under our control. However, simply removing them from target packages will not always work, because `--packages-above` argument is used and the vendor package might depend on a package that needs is tested. As a solution to this, `packages-skip` argument is introduces. It is not required and with the default value it will not change the workflow, so all of the current users will be unaffected.  
Tested with the packages skip for packages that do not pass the tests and confirmed that the workflow finishes successfully. 
Should not affect existing workflow who do not use the parameter. 
The PR reviewers …
=> feat: add packages to skip

colcon-test/action.yaml
This fixes colcon-test action to source underlay_ws before running rosdep install. Otherwise, it will fail to resolve rosdep keys for packages that exists in underlay workspace. 
This is already done in [colcon-build](https://github.com/autowarefoundation/autoware-github-actions/blob/92257e20a635042be7ea724593ee92a390b9b081/colcon-build/action.yaml#L92), but wasn't done in colcon-test action. 
Test with [this branch](https://github.com/mitsudome-r/tier4_ad_api_adaptor/tree/fix-build-ci) in this action https://github.com/mitsudome-r/tier4_ad_api_adaptor/actions/runs/14378069943/job/40315140715
None
The PR author **must** check the …
=> fix(colcon-test): source underlay_ws before running rosdep install

sync-branches/README.md, sync-branches/action.yaml
Sometimes it is useful to be able to sync branches from an outside location of the repo in question. For example, when we try to orchestrate multiple syncs from a centralized location. This PR adds optional `base-repo` input field to achieve the goal of syncing from outside location. 
Additionally, it sets created PR link to the output so that it is available for the caller.
This PR was tested on existing workflow: [TierIV link](https://github.com/tier4/autoware_launch.xx1/actions/runs/15014560571/job/42189468185)
Also, new functionality is already used from the PR branch in new workflow: [TIER IV link ](https://github.com/tier4/autoware-release-scripts/blob/b5311bc793e546ce4d6457226031d33d6f5ba7d0/.github/workflows/trigger-autoware-update-branch-product.yaml#L228)
No affect on existing …
=> feat: allow remote sync

sync-branches/README.md, sync-branches/action.yaml
This PR enhances the sync-branches GitHub Action by adding a new `pr-body-header` input parameter that allows users to add custom text before the automatically generated changelog in PR descriptions.
- Added `pr-body-header` input parameter
- Refactored and renamed the "Replace PR number to URL" step to "Prepare PR body" for better clarity
- Updated documentation in README.md to reflect the new parameter and provide usage examples
The new parameter allows for better customization of PR descriptions:
```yaml
- name: Run sync-branches
uses: autowarefoundation/autoware-github-actions/sync-branches@v1
with:
token: ${{ steps.generate-token.outputs.token }}
base-branch: main
sync-target-repository: https://github.com/autowarefoundation/autoware.git
sync-target-branch: main
sync-pr-branch: …
```
=> feat: add PR body header for sync branches

clang-tidy/action.yaml, colcon-build/action.yaml
This PR is a workaround of ROS signing key migration problem.
https://discourse.ros.org/t/ros-signing-key-migration-guide/43937/23
Once ros:humble and ros:jazzy are updated, we will revert this PR.
- https://github.com/autowarefoundation/autoware_internal_msgs/pull/68
- https://github.com/autowarefoundation/autoware_internal_msgs/actions/runs/15408429862 …
=> fix(build-and-test*.yaml): workaround of ROS signing key migration

bump-new-version/README.md, bump-new-version/action.yaml
Fix following bugs for `bump-new-version` workflow:
- Input variable name is inconsistent that of `README.md`
- Poor description
- Any string can be used for `bump_version`
- https://github.com/autowarefoundation/autoware-github-actions/pull/348
I used the following workflow:
- https://github.com/autowarefoundation/autoware_dummy_repository/blob/f786d6496ff2873a8ceca5edb32db2bb608c7d39/.github/workflows/bump-new-version.yaml
Then verified the manually triggered workflow succeeded:
- https://github.com/autowarefoundation/autoware_dummy_repository/actions/runs/15411385937
- https://github.com/autowarefoundation/autoware_dummy_repository/actions/runs/15411418128
:warning: If you are already using the `bump-new-version`, you need to update so it uses not `repository_owner` but …
=> fix(bump-new-version): bugs in version control workflows
