.github/create-doc-comment.sh
.github/get-modified-packages.sh
.github/workflows/pre-commit.yaml
.pre-commit-config.yaml

To fix this error.
https://results.pre-commit.ci/run/github/429694607/1638877268.AkhVVtz6SGiwbOWUN8pigw

ci(pre-commit): fix pre-commit-config.yaml for pre-commit.ci

---

.github/workflows/test-composite-actions.yaml
pre-commit/README.md
register-autonomoustuff-repository/README.md
register-autonomoustuff-repository/action.yaml

feat: add resister-autonomoustuff-repository action

---

.github/workflows/test-composite-actions.yaml
clang-tidy/action.yaml

fix(clang-tidy): add empty target check

---

deploy-docs/create-doc-comment.sh

Resolves #24 
```sh
~/ghq/github.com/autowarefoundation/autoware-documentation add-documentation-tree-structure
❯ ~/ghq/github.com/autowarefoundation/autoware-github-actions/deploy-docs/create-doc-comment.sh https://autowarefoundation.github.io/autoware-documentation/pr-14/ tier4/proposal
::set-output name=comment-body::Documentation URL: https://autowarefoundation.github.io/autoware-documentation/pr-14/
Modified URLs:
- https://autowarefoundation.github.io/autoware-documentation/pr-14/contributing/coding-guidelines/
- https://autowarefoundation.github.io/autoware-documentation/pr-14/contributing/coding-guidelines/languages/cmake/
- https://autowarefoundation.github.io/autoware-documentation/pr-14/contributing/coding-guidelines/languages/cpp/
- …
```

Handle a special case "index.md"

---

.github/workflows/test-composite-actions.yaml

ci: add test for colcon-build-and-test

---

check-file-existence/README.md

Related
https://github.com/autowarefoundation/autoware_common/pull/15#discussion_r797184761

docs(check-file-existence): fix usage

---

clang-tidy/action.yaml
colcon-build-and-test/action.yaml
delete-closed-pr-docs/action.yaml
deploy-docs/action.yaml
sync-branches/action.yaml
sync-files/action.yaml

With this, it can sync with private repositories.
I've tested it in our private repository.

fix(sync-branches, sync-files): set git config for private repositories

---

sync-files/action.yaml
sync-files/parse_config.py

- Rename variables
- Fix syntax errors
- Replace `dict.get(key)` with `key in dict`
- `get()` doesn't work with `False`

fix(sync-files): fix bugs

---

sync-files/README.md
sync-files/action.yaml

It is useful if we can know briefly what has changed.

feat(sync-files): add body

---

generate-changelog/README.md
generate-changelog/action.yaml

Split `generate-changelog` action from #38.

feat: add generate-changelog action

---

sync-branches/README.md
sync-branches/action.yaml

Similar to #52, it is useful if we can know what has changed.

feat(sync-branches): add changelog to body

---

get-modified-packages/get-modified-packages.sh

This PR is the solution same as #59 with less diff.

fix(get-modified-packages): fix a bug with top-level project repositories

---

.github/workflows/semantic-pull-request.yaml

Added by https://github.com/amannn/action-semantic-pull-request/pull/160

ci(semantic-pull-request): add validateSingleCommitMatchesPrTitle

---

clang-tidy/README.md
colcon-build-and-test/README.md
register-autonomoustuff-repository/README.md

docs: add article to ros distro

---

cliff.toml
generate-changelog/action.yaml

Waiting for https://github.com/kenji-miyake/setup-git-cliff/runs/5129805573?check_suite_focus=true.
And it's waiting for https://github.com/orhun/git-cliff/pull/59.

perf(generate-changelog): use setup-git-cliff to speed up

---

sync-branches/action.yaml

fix(sync-branches): check out with fetch-depth=0 to generate changelog

---

clang-tidy/action.yaml
colcon-build-and-test/action.yaml
colcon-build/action.yaml
colcon-test/action.yaml

This PR is to fix this error below.
https://github.com/tier4/autoware.universe/runs/5189371488?check_suite_focus=true

fix: add -p option to avoid mkdir error

---

clang-tidy/README.md
colcon-build-and-test/README.md
colcon-build/README.md
colcon-test/README.md
delete-closed-pr-docs/README.md
deploy-docs/README.md
generate-changelog/README.md
get-modified-packages/README.md
get-self-packages/README.md
pre-commit/README.md
register-autonomoustuff-repository/README.md
remove-exec-depend/README.md
spell-check/README.md
sync-branches/action.yaml
sync-files/action.yaml

chore(deps): bump actions/checkout from 2 to 3

---

README.md
check-file-existence/README.md
clang-tidy/README.md
clang-tidy/action.yaml
colcon-build/README.md
colcon-build/action.yaml
colcon-test/README.md
colcon-test/action.yaml
delete-closed-pr-docs/README.md
delete-closed-pr-docs/action.yaml
deploy-docs/README.md
deploy-docs/action.yaml
generate-changelog/README.md
generate-changelog/action.yaml
get-modified-packages/README.md
get-self-packages/README.md
pre-commit/README.md
register-autonomoustuff-repository/README.md
remove-exec-depend/README.md
set-git-config/README.md
spell-check/README.md
sync-branches/README.md
sync-branches/action.yaml
sync-files/README.md
sync-files/action.yaml

This PR should be merged when we release `v1`.

feat: use v1 instead of tier4/proposal

---

.github/workflows/github-release.yaml
.github/workflows/pre-commit-optional.yaml
.github/workflows/pre-commit.yaml
.github/workflows/spell-check-differential.yaml
.github/workflows/sync-files.yaml

This PR should be merged after #85.

ci: use v1 instead of tier4/proposal

---

deploy-docs/README.md
deploy-docs/action.yaml

It is useful to have an option to update `latest`.

feat(deploy-docs): add an option to create the 'latest' alias

---

sync-files/action.yaml

fix(sync-files): create the parent directory before copying a file

---

sync-files/parse_config.py

See https://github.com/autowarefoundation/autoware/pull/110#issuecomment-1076275755.

fix(sync-files): support empty settings

---

deploy-docs/action.yaml

fix(deploy-docs): fix a missing correction

---

.github/workflows/test-composite-actions.yaml
tests/dummy_packages/empty_target_cmake/CMakeLists.txt
tests/dummy_packages/empty_target_cmake/package.xml
tests/dummy_packages/empty_target_python/package.xml
tests/dummy_packages/empty_target_python/setup.cfg
tests/dummy_packages/empty_target_python/setup.py
tests/dummy_packages/empty_target_python/test/test_copyright.py
tests/dummy_packages/empty_target_python/test/test_flake8.py
tests/dummy_packages/empty_target_python/test/test_pep257.py

It's necessary for testing #134.
I've created these packages using the following commands:
```bash
ros2 pkg create --build-type ament_cmake empty_target_cmake
ros2 pkg create --build-type ament_python empty_target_python
```

test: add dummy packages for tests

---

.github/workflows/test-composite-actions.yaml
get-modified-packages/action.yaml

The action was broken for some reasons.
https://github.com/autowarefoundation/autoware.universe/runs/6058014488?check_suite_focus=true#step:6:1

test(get-modified-packages): add tests

---

sync-files/action.yaml

Upgraded to the latest version.
https://github.com/mikefarah/yq/releases/tag/v4.25.1
The `e` option can be removed after `v4.18`.
https://github.com/mikefarah/yq/releases/tag/v4.18.1

chore: upgrade yq to v4.25.1

---

colcon-test/action.yaml

Fix the CI error found in https://github.com/autowarefoundation/autoware-github-actions/pull/160#issuecomment-1149206292.

fix(colcon-test): fix dependencies of Python packages

---

deploy-docs/mkdocs-requirements.txt

[mkdocs-static-i18n](https://github.com/ultrabug/mkdocs-static-i18n) is an extension that supports multi languages.
> **Note**
> There is a small bug with the `navigation.instant` feature. https://github.com/ultrabug/mkdocs-static-i18n/issues/115

feat(deploy-docs): add mkdocs-static-i18n

---

.github/workflows/prevent-no-label-execution.yaml

It is easier for users to understand what label to be added.
Reference: https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-a-notice-message

feat(prevent-no-label-execution): use notice message

---

.github/dependabot.yaml
README.md
update-codeowners-from-packages/README.md
update-codeowners-from-packages/action.yaml

Add an action to update CODEOWNERS automatically.
For more details, please refer to https://github.com/autowarefoundation/autoware.universe/pull/1619.

feat: add an action 'update-codeowners-from-package'

---

clang-tidy/README.md

chore: fix typo

---

check-file-existence/README.md
check-file-existence/action.yaml
colcon-test/action.yaml

When we specify one file, it's useful if the default value is used.

feat(check-file-existence): make condition optional

---

pre-commit-autoupdate/README.md
pre-commit-autoupdate/action.yaml

It's useful for updating `.pre-commit-config-optional.yaml` and `.pre-commit-config-ansible.yaml`

feat: add a new action 'pre-commit-autoupdate'

---

.github/workflows/test-composite-actions.yaml

Autoware has transitioned to Humble.
https://github.com/autowarefoundation/autoware/discussions/2622

ci: update rosdistro to humble

---

cliff.toml

To adapt the interface of https://github.com/orhun/git-cliff/releases/tag/v1.0.0.

chore(cliff.toml): replace date_order with topo_order

---

deploy-docs/mkdocs-requirements.txt

Signed-off-by: M. Fatih Cırıt <mfc@leodrive.ai>
Let's support embedded videos in our documentation.
https://pypi.org/project/mkdocs-video/
Related to: https://github.com/autowarefoundation/autoware-documentation/pull/281/files#r1056538759

feat(deploy-docs): add mkdocs-video

---

set-cuda-path/README.md
set-cuda-path/action.yaml

See https://github.com/autowarefoundation/autoware/pull/3251.

feat: add set cuda path action

---

spell-check/action.yaml

See https://github.com/tier4/autoware-spell-check-dict/pull/475.
Since it just installs a package, it's not affected unless you import the file in your `.cspell.json`.

feat(spell-check): install autoware-spell-check-dict

---

.github/dependabot.yaml

chore: update dependabot.yaml

---

pre-commit-autoupdate/action.yaml
sync-branches/action.yaml
sync-files/action.yaml
update-codeowners-from-packages/action.yaml

There was a mistake in https://github.com/autowarefoundation/autoware-github-actions/pull/217.

fix: fix incorrect option of GitHub CLI

---

sync-files/action.yaml

Fix for the mistake in https://github.com/autowarefoundation/autoware-github-actions/pull/212.

fix(sync-files): add missing condition

---

.github/workflows/check-secret.yaml
.github/workflows/github-release.yaml
.github/workflows/prevent-no-label-execution.yaml
check-file-existence/action.yaml
clang-tidy/action.yaml
colcon-test/action.yaml
delete-closed-pr-docs/action.yaml
deploy-docs/action.yaml
deploy-docs/create-doc-comment.sh
generate-changelog/action.yaml
get-modified-packages/action.yaml
get-modified-packages/get-modified-packages.sh
get-self-packages/action.yaml
sync-branches/action.yaml
sync-files/action.yaml

refactor: replace set-output with $GITHUB_OUTPUT

---

deploy-docs/mkdocs-requirements.txt

Fix markdown version for deploy_docs
Failed CI: https://github.com/autowarefoundation/autoware-documentation/actions/runs/5678749882
> INFO    -  Doc file 'index.md' contains an unrecognized relative link 'installation', it was left as is. Did you mean 'installation/index.md'?
INFO    -  Doc file 'index.md' contains an unrecognized relative link 'tutorials', it was left as is. Did you mean 'tutorials/index.md'?
INFO    -  Doc file 'index.md' contains an unrecognized relative link 'how-to-guides', it was left as is. Did you mean 'how-to-guides/index.md'?
INFO    -  Doc file 'index.md' contains an unrecognized relative link 'design', it was left as is. Did you mean 'design/index.md'?
INFO    -  Doc file 'index.md' contains an unrecognized relative link 'contributing', it was left as is. Did …

fix(deploy_docs): fix mkdocs version

---

deploy-docs/mkdocs-requirements.txt

This adds tabulate module to mkdocs requirements.
This is needed to generate markdown table from JSON schema file for ROS node parameters.
Example: https://github.com/autowarefoundation/autoware.universe/pull/4656

feat(mkdocs): add tabulate to mkdocs-requirements.txt

---

deploy-docs/mkdocs-requirements.txt

This fixes the ordering of the top menu in Autoware Documentation to be the order specified by [.pages](https://github.com/autowarefoundation/autoware-documentation/blob/main/docs/.pages) file.
Run the following command:
1. Clone autoware-github-action repository: `git clone https://github.com/autowarefoundation/autoware-github-actions`
3. Install requirements for mkdocs: `pip install -r autoware-github-actions/deploy-docs/mkdocs-requirements.txt`
2. Clone autoware documentation repository: `git clone https://github.com/autowarefoundation/autoware-documentation`
4. `cd autoware-documentation`
5. build and run mkdocs: `mkdocs build; mkdocs serve`
6. with a browser, access to http://127.0.0.1:8000/autoware-documentation/
Before PR:
After PR:
The PR author **must** check the …

fix(deploy-docs): fix version for mkdocs-awesome-pages-plugin

---

generate-changelog/action.yaml

This PR sets `version` and `token` of https://github.com/kenji-miyake/setup-git-cliff/blob/main/action.yaml#L5-L12
When I set `version` and `token` like following, 
https://github.com/tier4/update-release-notes/blob/b425eb7d0affb4b1b0561a70aef825c8b0789783/create_release_note/action.yaml#L106-L107
Github Action works as we expected.
- Case 1. Set specific version and token.
https://github.com/tier4/update-release-notes/actions/runs/6446513529/job/17501785215#step:4:842
- Case 2. Not set version and token.
https://github.com/shmpwk/autoware-github-actions/actions/runs/6451995742/job/17513367115#step:6:38
The PR author **must** check …

feat(generate-changelog): set version and token of setup-git-cliff

---

.gitignore

Add simple gitignore or VSCode and JetBrains editors

chore(gitignore): add gitignore file

---

pre-commit/action.yaml

The pre-commit should work to already existing files.
https://github.com/stefanzweifel/git-auto-commit-action/blob/master/action.yml#L19-L22
(TIER IV Internal Link) https://tier4.atlassian.net/browse/RT0-31294

ci(pre-commit): only work to already existing files

---

clang-tidy/action.yaml

This PR is the `clang-tidy` version of https://github.com/autowarefoundation/autoware-github-actions/pull/337 https://github.com/autowarefoundation/autoware-github-actions/pull/340.
- https://github.com/autowarefoundation/autoware_core/pull/340
- https://github.com/autowarefoundation/autoware_core/actions/runs/14368001627?pr=340 …

feat(clang-tidy): source `${{ inputs.underlay-workspace }}/setup.sh` if exists

---

colcon-build/action.yaml
colcon-test/action.yaml

- Resolves: https://github.com/autowarefoundation/autoware-github-actions/issues/344
- https://github.com/autowarefoundation/autoware_universe/pull/10650
- https://github.com/autowarefoundation/autoware_universe/actions/runs/15087742105/job/42412454193#step:15:385
```
Run echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
GITHUB_WORKSPACE: /__w/autoware_universe/autoware_universe
fetching default: file:///__w/autoware_universe/autoware_universe/colcon-mixin-repository/index.yaml ...
fetching file:///__w/autoware_universe/autoware_universe/colcon-mixin-repository/asan.mixin ...
. /github/home/.colcon/mixin/default/asan.mixin
fetching file:///__w/autoware_universe/autoware_universe/colcon-mixin-repository/build-testing.mixin ...
+ /github/home/.colcon/mixin/default/build-testing.mixin
fetching …
```

feat: add local colcon mixin option

---

colcon-build/action.yaml
colcon-test/action.yaml

- resolves https://github.com/autowarefoundation/autoware-github-actions/issues/344
This bug has reoccured recently:
- https://github.com/autowarefoundation/autoware_universe/actions/runs/15126042646/job/42518172598#step:15:278

feat(colcon-build-test): cache rosdep update to avoid rate limits

---

bump-new-version/action.yaml

This PR provides a feature for `bump-new-version` workflow added in the following PR to resolve conflicts automatically.
- https://github.com/autowarefoundation/autoware-github-actions/pull/348
We performed the tests by using [experimental purpose use repository](https://github.com/autowarefoundation/autoware_dummy_repository) to trigger the workflow directly. 
- As this PR provides a feature to resolve conflicts automatically, we tested:
- Tested with conflicts
- https://github.com/autowarefoundation/autoware_dummy_repository/actions/runs/15627187170
- Tested without conflicts
- https://github.com/autowarefoundation/autoware_dummy_repository/actions/runs/15628116100
Perhaps the performed tests are not sufficient. Please feel free to share any comments and proposals, I'm happy for …

feat(bum-new-version): handle merge conflict in release tag

---

deploy-docs/action.yaml
deploy-docs/mkdocs-requirements.txt

- Reopened: https://github.com/autowarefoundation/autoware-github-actions/pull/355
@evshary 's solution.

feat(deploy-docs): fix deploy failure
